In [2]:
import pandas as pd
import numpy as np

In [3]:
teamMembers = [
    { "name": "Shreyash Bhute", "post": "Jr. Operations Officer" , "cgpa":10},
    { "name": "Arya Madhavi", "post": "Jr. Operations Officer", "mail": "2022.arya.madhavi@ves.ac.in" , "cgpa":10 },
    { "name": "Surel Sanap", "post": "Jr. Public Relations Officer", "mail": "2022.surel.sanap@ves.ac.in"  , "cgpa":10},
    { "name": "Simran Godhwani", "post": "Jr. Public Relations Officer", "mail": "2022.simran.godhwani@ves.ac.in"  , "cgpa":9},
    { "cgpa":8},
    { "name": "Aditya Kumar", "post": "Jr. Web Editor", "mail": "2022.aditya.sampathkumar@ves.ac.in"  , "cgpa":9},
    { "name": "Karan Bhatia", "post": "Jr. Web Editor", "mail": "2022.karan.bhatia@ves.ac.in"  , "cgpa":8},
    { "name": "Sami Thakur", "post": "Jr. Technical Officer", "mail": "2022.sami.thakur@ves.ac.in"  , "cgpa":9},
    { "name": "Sagar Rajak", "post": "Jr. Technical Officer", "mail": "2022.sagar.rajak@ves.ac.in"  , "cgpa":8},
    {"name":""  , "cgpa":10},
    { "name": "Anish Padhye", "post": "Jr. Editor", "mail": "2022.anish.padhye@ves.ac.in" , "cgpa":9 },
]

In [4]:
df= pd.DataFrame(teamMembers)

In [5]:
df

,name,post,cgpa,mail
0,Shreyash Bhute,Jr. Operations Officer,10,NaN
1,Arya Madhavi,Jr. Operations Officer,10,2022.arya.madhavi@ves.ac.in
2,Surel Sanap,Jr. Public Relations Officer,10,2022.surel.sanap@ves.ac.in
3,Simran Godhwani,Jr. Public Relations Officer,9,2022.simran.godhwani@ves.ac.in
4,NaN,NaN,8,NaN
5,Aditya Kumar,Jr. Web Editor,9,2022.aditya.sampathkumar@ves.ac.in
6,Karan Bhatia,Jr. Web Editor,8,2022.karan.bhatia@ves.ac.in
7,Sami Thakur,Jr. Technical Officer,9,2022.sami.thakur@ves.ac.in
8,Sagar Rajak,Jr. Technical Officer,8,2022.sagar.rajak@ves.ac.in
9,,NaN,10,NaN
10,Anish Padhye,Jr. Editor,9,2022.anish.padhye@ves.ac.in

In [6]:
df["post"].value_counts()

post
Jr. Operations Officer          2
Jr. Public Relations Officer    2
Jr. Web Editor                  2
Jr. Technical Officer           2
Jr. Editor                      1
Name: count, dtype: int64

In [7]:
df.groupby(["post","cgpa"]).sum()
# all agregation model #
df.groupby(["post","cgpa"]).describe().transpose()

post                          Jr. Editor       Jr. Operations Officer  \
cgpa                                  9                            10
name count                             1                            2
     unique                            1                            2
     top                    Anish Padhye               Shreyash Bhute
     freq                              1                            1
mail count                             1                            1
     unique                            1                            1
     top     2022.anish.padhye@ves.ac.in  2022.arya.madhavi@ves.ac.in
     freq                              1                            1

post           Jr. Public Relations Officer                              \
cgpa                                     9                           10
name count                                1                           1
     unique                               1                           1
     top                    Simran Godhwani                 Surel Sanap
     freq                                 1                           1
mail count                                1                           1
     unique                               1                           1
     top     2022.simran.godhwani@ves.ac.in  2022.surel.sanap@ves.ac.in
     freq                                 1                           1

post              Jr. Technical Officer                              \
cgpa                                 8                           9
name count                            1                           1
     unique                           1                           1
     top                    Sagar Rajak                 Sami Thakur
     freq                             1                           1
mail count                            1                           1
     unique                           1                           1
     top     2022.sagar.rajak@ves.ac.in  2022.sami.thakur@ves.ac.in
     freq                             1                           1

post                      Jr. Web Editor
cgpa                                  8                                   9
name count                             1                                   1
     unique                            1                                   1
     top                    Karan Bhatia                        Aditya Kumar
     freq                              1                                   1
mail count                             1                                   1
     unique                            1                                   1
     top     2022.karan.bhatia@ves.ac.in  2022.aditya.sampathkumar@ves.ac.in
     freq                              1                                   1

In [15]:
gr = df.groupby(["cgpa","post"]).sum()
gr.index.levels
gr

                                                         name  \
cgpa post
8    Jr. Technical Officer                        Sagar Rajak
     Jr. Web Editor                              Karan Bhatia
9    Jr. Editor                                  Anish Padhye
     Jr. Public Relations Officer             Simran Godhwani
     Jr. Technical Officer                        Sami Thakur
     Jr. Web Editor                              Aditya Kumar
10   Jr. Operations Officer        Shreyash BhuteArya Madhavi
     Jr. Public Relations Officer                 Surel Sanap

                                                                 mail
cgpa post
8    Jr. Technical Officer                 2022.sagar.rajak@ves.ac.in
     Jr. Web Editor                       2022.karan.bhatia@ves.ac.in
9    Jr. Editor                           2022.anish.padhye@ves.ac.in
     Jr. Public Relations Officer      2022.simran.godhwani@ves.ac.in
     Jr. Technical Officer                 2022.sami.thakur@ves.ac.in
     Jr. Web Editor                2022.aditya.sampathkumar@ves.ac.in
10   Jr. Operations Officer               2022.arya.madhavi@ves.ac.in
     Jr. Public Relations Officer          2022.surel.sanap@ves.ac.in

In [17]:
gr.loc[(10 , "Jr. Public Relations Officer")]

name                   Surel Sanap
mail    2022.surel.sanap@ves.ac.in
Name: (10, Jr. Public Relations Officer), dtype: object

In [23]:
gr.xs(key=10 , level="cgpa")
gr.loc[[9,10],"name"]
gr.xs(key="Jr. Technical Officer" , level="post")

             name                        mail
cgpa
8     Sagar Rajak  2022.sagar.rajak@ves.ac.in
9     Sami Thakur  2022.sami.thakur@ves.ac.in

In [39]:
new = df[df["cgpa"].isin([9,10])].groupby(["cgpa","post"]).sum()
new.swaplevel()
# df.agg(["std","mean"])

TypeError: could not convert string to float: 'Shreyash Bhute'